[phases.setup]
nixpkgs = ["jdk21", "gradle"]

[phases.build]
cmds = ["./gradlew clean build -x test"]

[start]
cmd = "java -jar $(find build/libs -name '*SNAPSHOT.jar' ! -name '*plain.jar' | head -n 1)"
